# Generated by Django 6.1 on 2026-08-26 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدير النظام'), ('delegate', 'مندوب مبيعات')], default='delegate', max_length=20, verbose_name='الصلاحية')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('print_names', models.BooleanField(default=True, verbose_name='طباعة الأسماء')),
                ('print_phones', models.BooleanField(default=True, verbose_name='طباعة الهواتف')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المندوب')),
            ],
        ),
    ]
