# Generated by Django 6.1 on 2026-08-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delegateprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegateprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم جوال النظام الداخلي'),
        ),
        migrations.AlterField(
            model_name='delegateprofile',
            name='print_names',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الأسماء المطبوعة على الفاتورة'),
        ),
        migrations.AlterField(
            model_name='delegateprofile',
            name='print_phones',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الأرقام المطبوعة على الفاتورة'),
        ),
    ]
