# Generated by Django 6.1 on 2026-09-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_delegateprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_limit',
            field=models.IntegerField(default=5, verbose_name='الحد الأدنى للتنبيه'),
        ),
    ]
